version: 0.2

phases:
  install:
    commands:
      # Install NVM
      - echo "Installing NVM..."
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
      - export NVM_DIR="$HOME/.nvm" 
      - [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" 
      - nvm --version 
      # Install Node.js 10.24.1 using NVM
      - nvm install 10.24.1
      - nvm use 10.24.1  # Switch to Node.js version 10.24.1
      - nvm alias default 10.24.1  # Set it as the default version
      - node -v  # Verify the Node.js version installed

  pre_build:
    commands:
      - echo "Installing source NPM dependencies..."
      # - npm install  # Uncomment if you need to install dependencies here

  build:
    commands:
      - echo "Building the project..."
      - gem install ffi -v 1.16.3
      - gem install sass
      - npm install --global gulp-cli
      - npm install -g @angular/cli@10.2.4
      - npm install
      - gulp sass
      - gulp views
      - ng build --configuration=${env} --verbose

  post_build:
    commands:
      - bash -c "if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"0/" ]; then exit 1; fi"
      - aws s3 rm s3://${S3_BUCKET_COCKPIT} --recursive
      - aws s3 cp dist/Cockpit-FE s3://${S3_BUCKET_COCKPIT} --recursive --acl public-read
      - aws cloudfront create-invalidation --distribution-id ${CF_DISTRIBUTION_COCKPIT} --paths "/*"
      - echo "Build completed on $(date)"

artifacts:
  files:
    - '**/*'
  base-directory: dist/Cockpit-FE
