export const environment: any = {
    production: true,
    env: 'production',
    appDomain: 'appcockpit.parkstreet.com',
    appRoute: 'https://appcockpit.parkstreet.com',
    version: { v1: 'v1/', v2: 'v2/' },
    newLoginUrl: '/login',
    newSignupUrl: '/user-signup',
    loginUrl: 'login',
    apiUrl: 'https://api.parkstreet.com/v1/',
    apiRouteUrl: 'https://api.parkstreet.com/',
    pictureUrl: 'https://navigator.parkstreet.com/uploads/crm/',
    personUrl: '/router.php/people/profile/',
    fileServer: 'https://navigator.parkstreet.com',
    oldNavigator: 'https://navigator.parkstreet.com',
    oldCockpit: 'https://cockpit.parkstreet.com',
    hotjar: '1444748',
    host: window.location.hostname,
  };
