export const environment = {
  production: false,
  env: 'local',
  cloudFrontUrl: '' ,
  version: {v1: 'v1/', v2: 'v2/'},
  googleAnalytics: 'UA-123706474-1',
  googleTagManager: 'UA-151603696-3',
  hotjar: '1565856',
  linkedAppClientId: '86v6oavqh93pom',
  googleAppClientId: '447267132714-k7abm5utbhfon7magcj615kc8mlinl80.apps.googleusercontent.com',
  appleAppClientId: 'com.staging.parkstreet',
  newLoginUrl: '/login',
  newSignupUrl: '/user-signup',
  loginUrl: 'login',
 // apiUrl: 'http://api.parkstreet.local/v1/',
  //  apiRouteUrl: 'http://api.parkstreet.local/',
   apiUrl: 'https://stgapi.parkstreet.com/v1/',
 apiRouteUrl: 'https://stgapi.parkstreet.com/',
  // apiUrl: 'http://apinavigator.parkstreet.local/v1/',
  // apiRouteUrl: 'http://apinavigator.parkstreet.local/',
  pictureUrl: 'https://stgnavigator.parkstreet.com/uploads/crm/',
  personUrl: '/router.php/people/profile/',
  // fileServer: 'http://navigator.parkstreet.local',
  fileServer: 'https://stgnavigator.parkstreet.com',
  // oldNavigator: 'http://navigator.parkstreet.local',
  oldNavigator: 'https://stgnavigator.parkstreet.com',
  oldCockpit: 'https://stgcockpit.parkstreet.com',
  satismeterKey: '1KnYa8ePvL1A1wE6',
  segmentKey: 'ho1DjJ5yr2ta8PuArLRAgaxqkEd5ARzA',
  host: (window.location.hostname === 'localhost') ? window.location.hostname + '/Navigator-FE' : window.location.hostname,
  stonlyId: '9455c200-b51b-11ec-9fb8-0ae9fa2a18a2',
  socketUrl: 'wss://stgws.parkstreet.com/chat',
  stripeKey: 'pk_test_51Hzg6NG3qi1rhSM7eYvfqKokvoHEbfee0cSwUEjQ9TCCpNWv2TJgNNcuZ7CpfWSjjzZniJrHLh5AeLWUaRxE1k0e00UMm7mYUT'
};